# Generated by Django 3.1.5 on 2022-09-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('day_event', models.DateField()),
                ('total_enrolled', models.DecimalField(decimal_places=0, default=50, max_digits=2)),
                ('enrolled', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
            ],
        ),
    ]
