# Generated by Django 3.1.5 on 2022-09-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='events',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
